// Layout captures with stubbed API data (MOCK-not-jev). Usage: vite preview --port 4179 running, then node harness/evidence-budget/shot.mjs <outdir>
import{chromium}from'@playwright/test';import{readFileSync}from'node:fs';
const out=process.argv[2]||'.';const {cohort,run}=JSON.parse(readFileSync(new URL('./mock-run.json',import.meta.url)));
const b=await chromium.launch();
for(const [name,vp] of [['320',{width:320,height:720}],['375',{width:375,height:812}],['390',{width:390,height:844}],['1440',{width:1440,height:1000}],['1920',{width:1920,height:1080}]]){const p=await b.newPage({viewport:vp});await p.route('**/api/run-evidence-budget',r=>r.request().method()==='GET'?r.fulfill({json:cohort}):r.fulfill({json:run}));await p.goto('http://localhost:4179/apps/evidence-budget');await p.waitForSelector('.eb-note');await p.screenshot({path:`${out}/eb-${name}-initial-MOCKDATA.png`});await p.click('.eb-run');await p.waitForSelector('.eb-receipt',{timeout:8000});await p.waitForTimeout(500);await p.screenshot({path:`${out}/eb-${name}-result-MOCKDATA.png`,fullPage:true});
const m=await p.evaluate(()=>({overflowX:document.documentElement.scrollWidth-innerWidth,smallTargets:[...document.querySelectorAll('main button,main select,main textarea')].filter(e=>{const r=e.getBoundingClientRect();return r.height<44}).map(e=>e.className||e.tagName),textareaFontPx:getComputedStyle(document.querySelector('textarea')).fontSize,attributionVisible:(()=>{const e=document.querySelector('.eb-aside');const r=e.getBoundingClientRect();return getComputedStyle(e).display!=='none'&&r.height>0})()}));console.log(name,JSON.stringify(m));await p.close()}
{const mrun=JSON.parse(JSON.stringify(run));for(const r of mrun.rounds)for(const c of (r.scores||[]))if(c.id==='m05'){c.mismatch=true;c.expectedFromProbabilities=1.2}
const p=await b.newPage({viewport:{width:1440,height:1000}});await p.route('**/api/run-evidence-budget',r=>r.request().method()==='GET'?r.fulfill({json:cohort}):r.fulfill({json:mrun}));await p.goto('http://localhost:4179/apps/evidence-budget');await p.waitForSelector('.eb-note');await p.click('.eb-run');await p.waitForSelector('.eb-receipt');await p.waitForTimeout(500);await p.screenshot({path:`${out}/eb-1440-mismatch-variant-MOCKDATA.png`});
const c=await p.evaluate(()=>{const lum=(rgb)=>{const [r,g,b]=rgb.match(/\d+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.03928?v/12.92:((v+.055)/1.055)**2.4});return .2126*r+.7152*g+.0722*b};const el=document.querySelector('.project-nav b');const fg=getComputedStyle(el).color;let n=el,bg='rgba(0, 0, 0, 0)';while(n&&(bg==='rgba(0, 0, 0, 0)'||bg==='transparent')){bg=getComputedStyle(n).backgroundColor;n=n.parentElement}const L1=lum(fg),L2=lum(bg);return{breadcrumb:el.textContent,fg,bg,contrast:((Math.max(L1,L2)+.05)/(Math.min(L1,L2)+.05)).toFixed(2),mismatchTags:document.querySelectorAll('.eb-tag.mismatch').length}});console.log('checks',JSON.stringify(c));await p.close()}
await b.close();
