import{useEffect,useState}from'react';import{Download,Network,Play,RefreshCw,TriangleAlert}from'lucide-react';import{ProjectNav}from'./ProjectNav';
type Note={id:string;date:string;source:string;text:string};type Cand={id:string;ok:boolean;normalized?:number;path?:string;raw?:number;reason?:string;mismatch?:boolean;expectedFromProbabilities?:number|null};
type Round={round:number;candidateIds:string[];scores?:Cand[];kept?:string[];pEnough?:number;nextView?:string;latencyMs:number;error?:string;invalid?:{reason:string}};
type Run={runId:string;seeds:string[];rounds:Round[];outcome:{stopReason:string;complete:boolean;warning:string|null;evidencePacket:Note[];controllerCalls:number;notesInspected:number;notesInMemory:number};check:null|{gold:string[];recall:number;precision:number;missing:string[];extra:string[]};cached?:boolean;economics:{jevInputTokens:number;jevTokenSource:string;jevEstimatedCostUsd:number;pricingSnapshot:{asOf:string;source:string;jevInputUsdPerMillion:number};answerContextTokensEstimated:{fullMemory:number;evidencePacket:number}};latency:{totalMs:number;perRoundMs:number[]};provenance:Record<string,string>;evidence:{replayCoreSha256:string;hashScope:string;replay:string}};
type Cohort={cohortSha256:string;memory:Note[];examples:{question:string;gold:string[]}[];policy:{version:string;rule:string}};
const stopText:Record<string,string>={controller_enough:'Jev judged the evidence sufficient',kept_cap:'Kept-note cap reached before Jev judged it enough',round_cap:'Round cap reached before Jev judged it enough',token_ceiling:'Per-request token ceiling reached before Jev judged it enough',graph_exhausted:'Links ran out before Jev judged it enough',invalid_enough_fail_closed:'Invalid P(enough): stopped fail-closed',invalid_view_fail_closed:'Invalid link choice: stopped fail-closed',no_seed_match:'No memory matched the question',controller_unavailable_fail_closed:'Jev unavailable: stopped fail-closed',invalid_score_fail_closed:'Invalid score: stopped fail-closed'};
const pct=(n:number)=>`${(n*100).toFixed(0)}%`;
export function EvidenceBudget(){const capture=new URLSearchParams(location.search).get('capture')==='1';const[cohort,setCohort]=useState<Cohort|null>(null);const[question,setQuestion]=useState('');const[run,setRun]=useState<Run|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[shown,setShown]=useState(0);
useEffect(()=>{fetch('/api/run-evidence-budget').then(r=>r.ok?r.json():Promise.reject()).then((c:Cohort)=>{setCohort(c);setQuestion(c.examples[0].question)}).catch(()=>setError('Could not load the frozen memory cohort.'))},[]);
useEffect(()=>{if(!run)return;setShown(0);const t=setInterval(()=>setShown(x=>{if(x>=run.rounds.length){clearInterval(t);return x}return x+1}),700);return()=>clearInterval(t)},[run]);

const go=async()=>{setBusy(true);setError('');setRun(null);try{const r=await fetch('/api/run-evidence-budget',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question})});if(!r.ok)throw Error(r.status===429?'Rate limit reached for this hour. Try an example question, which may return a cached receipt.':r.status===503?'Live runs are switched off or Jev is not configured on this deployment.':'The run failed. Questions must be 5 to 500 characters.');setRun(await r.json())}catch(e){setError(e instanceof Error?e.message:'Run failed')}finally{setBusy(false)}};
const visible=run?run.rounds.slice(0,shown):[];const inspected=new Set(visible.flatMap(r=>r.candidateIds));const allScores=visible.flatMap(r=>r.scores||[]);const kept=new Set(visible.at(-1)?.kept||[]);const done=run&&shown>=run.rounds.length;const final=done?new Set(run.outcome.evidencePacket.map(n=>n.id)):kept;
const download=()=>{if(!run)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(run,null,2)],{type:'application/json'}));a.download=`${run.runId}.json`;a.click();URL.revokeObjectURL(a.href)};
return <main className={`ebudget ${capture?'capture-mode':''}`}><ProjectNav current="/apps/evidence-budget" label="APP / EVIDENCE BUDGET"/>
<section className="eb-hero"><div><small>JEV MEMORY CONTROL</small><h1>Retrieve less.<br/><em>Keep the receipts.</em></h1><p>Jev scores each memory note, picks which kind of link to follow next, and says when there is enough. Code caps the search, keeps the original notes, and writes a replayable receipt. Nothing here writes an answer.</p></div><div className="eb-aside"><Network/><b>READ-PATH IDEA FROM JEV-MEM</b><span>Borrowed from <a href="https://arxiv.org/abs/2609.23986">Jiang, Li and Li (UT Dallas), arXiv 2609.23986</a>. Much smaller: 12 synthetic notes with hand-authored links, fixed caps, no write path or query routing.</span></div></section>
<section className="eb-work"><div className="eb-input"><small>QUESTION</small><div className="eb-examples">{cohort?.examples.map((e,i)=><button key={e.question} className={question===e.question?'on':''} onClick={()=>setQuestion(e.question)}>EXAMPLE {i+1}</button>)}</div><label htmlFor="eb-q" className="sr-only">Question about the memory</label><textarea id="eb-q" value={question} maxLength={500} onChange={e=>setQuestion(e.target.value)}/><button className="eb-run" onClick={go} disabled={busy||!cohort||question.trim().length<5}>{busy?<><RefreshCw className="spin"/> SEARCHING MEMORY…</>:<><Play/> RUN LIVE</>}</button>{error&&<p className="eb-error" role="alert"><TriangleAlert/>{error}</p>}
<div className="eb-policy"><small>FROZEN POLICY · {cohort?.policy.version}</small><p>{cohort?.policy.rule}</p><code>cohort {cohort?.cohortSha256.slice(0,16)}…</code></div></div>
<div className="eb-memory" aria-label="Memory notes">{cohort?.memory.map(n=>{const c=allScores.find(x=>x.id===n.id);const st=final.has(n.id)?'kept':inspected.has(n.id)?'seen':'idle';return <article key={n.id} className={`eb-note ${st}`}><div className="eb-nh"><b>{n.id}</b><span>{n.date} · {n.source}</span>{st!=='idle'&&<em className={`eb-tag ${st}`}>{st==='kept'?'KEPT':'SEEN'}</em>}{c?.mismatch&&<em className="eb-tag mismatch" title={`score ${c.raw} vs expected ${c.expectedFromProbabilities?.toFixed(2)} from probabilities`}>MISMATCH</em>}{c&&<i>{c.ok?`${pct(c.normalized||0)} · lvl ${(c.raw||0).toFixed(1)}`:'INVALID'}</i>}</div><p>{n.text}</p>{c?.ok&&<div className="eb-bar"><i style={{width:pct(c.normalized||0)}}/></div>}</article>})}</div></section>
<section className="eb-result" role="status" aria-live="polite">{!run&&!busy&&<p className="eb-empty">Run a question. Notes light up as Jev inspects them, and the ones it keeps turn blue and are tagged KEPT.</p>}{busy&&<p className="eb-empty"><RefreshCw className="spin"/> Jev is scoring candidates. One call per round, at most four rounds.</p>}
{run&&<><div className="eb-rounds">{visible.map((r,i)=><article key={r.round}><small>ROUND {r.round} · {run.latency.perRoundMs[i]??'-'}ms</small>{r.error||r.invalid?<b className="bad">{r.error||r.invalid?.reason}</b>:<><b>P(enough) {pct(r.pEnough||0)}</b><span>kept {r.kept?.join(', ')||'none'}{r.nextView&&` · next: ${r.nextView} links`}</span></>}</article>)}</div>
{done&&<><div className={`eb-stop ${run.outcome.complete?'':'warn'}`}><small>STOP REASON</small><b>{stopText[run.outcome.stopReason]||run.outcome.stopReason}</b>{run.outcome.warning&&<p className="eb-warn">{run.outcome.warning}</p>}<span>{run.cached?'CACHED RECEIPT · no new Jev calls · ':''}{run.outcome.controllerCalls} Jev call{run.outcome.controllerCalls===1?'':'s'} · {run.outcome.notesInspected} of {run.outcome.notesInMemory} notes inspected · {run.latency.totalMs}ms</span></div>
<div className="eb-metrics"><div><small>JEV READ (CONTROLLER INPUT)</small><b>{run.economics.jevInputTokens} tokens · est. ${run.economics.jevEstimatedCostUsd.toFixed(6)}</b><span>{run.economics.jevTokenSource==='provider_usage'?'provider-reported usage':'ESTIMATED tokens (chars/4)'} · ${run.economics.pricingSnapshot.jevInputUsdPerMillion}/M input, <a href={run.economics.pricingSnapshot.source}>public price</a> as of {run.economics.pricingSnapshot.asOf} · not charged spend</span></div><div><small>ANSWER-MODEL CONTEXT (EST.)</small><b>{run.economics.answerContextTokensEstimated.evidencePacket} vs {run.economics.answerContextTokensEstimated.fullMemory} tokens</b><span>packet vs whole memory, chars/4 estimate. On a 12-note memory the controller reads more than it saves; the trade only pays on large memories.</span></div>{run.check?<div><small>CHECK VS FROZEN GOLD</small><b>recall {pct(run.check.recall)} · precision {pct(run.check.precision)}</b><span>{run.check.missing.length?`missed ${run.check.missing.join(', ')}`:'no gold note missed'}{run.check.extra.length?` · extra ${run.check.extra.join(', ')}`:''}</span></div>:<div><small>CHECK</small><b>No gold set</b><span>Custom question: inspect the packet yourself.</span></div>}</div>
<div className="eb-receipt"><code title={run.evidence.hashScope}>replay-core sha256 {run.evidence.replayCoreSha256}</code><span>{run.provenance.controller} · {run.provenance.controllerRoute}</span><button onClick={download}><Download/> RECEIPT JSON</button></div></>}</>}</section></main>}
