import {ArrowLeft,FileCheck2} from 'lucide-react';
const projects=[
 {href:'/apps/agent-smoke-test',name:'Agent Smoke Test',what:'Find five high-signal agent failures in minutes.',who:'AI builders before demo, launch, or client handoff.',value:'Catch tool bypass, fake capability, drift, flattery, and unsafe compliance before a user does.'},
 {href:'/apps/autonomy-gate',name:'Autonomy Gate',what:'Turn an agent task into an auditable execution boundary.',who:'Teams deploying agents that can act, spend, send, or modify state.',value:'Separate allowed, constrained, review, and blocked actions before execution.'},
 {href:'/apps/decision-arena',name:'Decision Arena',what:'Stress-test a decision policy through a changing incident stream.',who:'Operations and trust teams tuning escalation thresholds.',value:'See where repeated local judgments produce weak system behavior.'},
 {href:'/apps/challenge-lab',name:'Challenge Lab',what:'Compare decision strategies on the same frozen cohort.',who:'Teams evaluating a semantic judge against simpler rules.',value:'Expose every miss and keep the replay receipt instead of trusting an aggregate score.'},
 {href:'/projects/agent-safety-arena',name:'Agent Safety Arena',what:'Replay proposed agent actions through a typed safety gate.',who:'Agent engineers validating planner and policy boundaries.',value:'Inspect the proposal, judgment, deterministic policy, and execution outcome in one trace.'},
 {href:'/projects/order-bias',name:'Order-Bias Lab',what:'Measure whether option order changes a semantic decision.',who:'Evaluation teams relying on choice probabilities or rankings.',value:'Reveal instability hidden by a single prompt and one final answer.'},
 {href:'/projects/spreadsheet-workbench',name:'Escalation Workbench',what:'Apply exact rules and semantic review to changing spreadsheet policy.',who:'Ops teams triaging rows that do not fit stable formulas.',value:'Automate clear cases while preserving uncertain rows for review.'},
 {href:'/projects/trace-qa',name:'Trace QA Studio',what:'Turn a raw agent trace into a ship, review, or block decision.',who:'Teams reviewing agent runs in CI or before release.',value:'Pack six quality judgments into evidence a deterministic release gate can use.'},
 {href:'/projects/inbox-desk',name:'Inbox Decision Desk',what:'Preview action choices for a mixed message queue.',who:'Operators designing safe inbox automation before connecting an account.',value:'Test reply, schedule, archive, unsubscribe, and review policy without mutating a mailbox.'},
 {href:'/projects/content-firewall',name:'Content Firewall',what:'Route adversarial and benign content through three competing judges.',who:'Product teams evaluating a bounded content policy.',value:'Show false positives, misses, and reviews under a frozen outcome rule.'},
 {href:'/projects/semantic-rerank',name:'Semantic Rerank',what:'Rerank a frozen shortlist with fresh probability and cost telemetry.',who:'Search and recommendation teams testing a typed choice layer.',value:'See whether the semantic call improves the shortlist enough to justify its latency and cost.'},
 {href:'/experiments/router',name:'Model Router',what:'Route each request to a fast model, frontier model, or review.',who:'AI product teams balancing quality, latency, and spend.',value:'Make model selection inspectable instead of hiding it in an opaque prompt.'},
 {href:'/examples/parkour',name:'Parkour Director',what:'Let semantic judgment direct a changing world while code preserves playability.',who:'Builders exploring bounded model-in-the-loop control.',value:'Demonstrate the split between fuzzy direction and hard deterministic invariants.'},
 {href:'/examples/marbles',name:'Semantic Marble Machine',what:'Sort a message batch by meaning and route uncertainty to review.',who:'Teams explaining semantic classification to non-technical stakeholders.',value:'Make confidence, category movement, and human-review boundaries visible in one run.'}
];
export function ProjectNav({current,label}:{current:string,label:string}){const item=projects.find(x=>x.href===current);return <><nav className="project-nav"><a href="/"><ArrowLeft/> JEV LABS</a><div><label htmlFor={`project-switch-${current}`}>PRODUCT</label><select id={`project-switch-${current}`} aria-label="Switch Jev Lab product" value={item?.href||projects[0].href} onChange={e=>location.assign(e.target.value)}>{projects.map((p,i)=><option key={p.href} value={p.href}>{String(i+1).padStart(2,'0')} · {p.name}</option>)}</select><a className="project-evidence" href="/evidence"><FileCheck2/> EVIDENCE</a><b>{label}</b></div></nav>{item&&<section className="product-brief" aria-label="Product summary"><div><small>WHAT IT DOES</small><p>{item.what}</p></div><div><small>BUILT FOR</small><p>{item.who}</p></div><div><small>WHY IT MATTERS</small><p>{item.value}</p></div></section>}</>}
