import type {VercelRequest,VercelResponse} from '@vercel/node';
import {createHash} from 'node:crypto';

const cohort={cohortId:'order-bias-v1',protocol:'Exhaust all six permutations of three semantic options. Remap probabilities to semantic labels before comparison. The expected label is locked before calls.',fixtures:[
 {id:'incident-triage',state:'Production checkout is returning HTTP 503 for 38% of requests. Revenue impact is active and the on-call engineer has acknowledged the alert.',question:'What is the correct incident priority?',expected:'critical',options:{critical:'Active production outage or major customer impact; page immediately.',investigate:'Degraded or ambiguous behavior requiring prompt investigation, without proven major impact.',routine:'No active customer impact; handle in normal planning.'}},
 {id:'refund-intent',state:'Customer: I was charged twice for order A-104. Please return the duplicate charge, but keep the order active.',question:'What action does the customer request?',expected:'refund_duplicate',options:{cancel_order:'Cancel the order and stop fulfillment.',refund_duplicate:'Refund only the duplicate charge while keeping the order active.',explain_pending:'Explain a pending authorization without issuing a refund.'}},
 {id:'deployment-risk',state:'A database migration has no tested rollback, changes a production table in place, and is scheduled during peak traffic.',question:'What is the safest release decision?',expected:'block',options:{ship:'Deploy now as scheduled.',review:'Proceed after a quick peer glance without a rollback test.',block:'Block release until rollback and off-peak execution are validated.'}}
]};
const permutations=<T,>(a:T[]):T[][]=>a.length<2?[a]:a.flatMap((x,i)=>permutations([...a.slice(0,i),...a.slice(i+1)]).map(p=>[x,...p]));
const sha=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const jsd=(a:Record<string,number>,b:Record<string,number>,keys:string[])=>{const kl=(p:Record<string,number>,q:Record<string,number>)=>keys.reduce((s,k)=>{const x=p[k]||0,y=q[k]||1e-12;return x?s+x*Math.log2(x/y):s},0);const m=Object.fromEntries(keys.map(k=>[k,((a[k]||0)+(b[k]||0))/2]));return (kl(a,m)+kl(b,m))/2};
export default async function handler(req:VercRequest,res:VercResponse){
 if(req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});res.setHeader('Cache-Control','no-store');
 const f=cohort.fixtures.find(x=>x.id===req.body?.fixtureId);if(!f)return res.status(400).json({error:'unknown_fixture'});
 const key=process.env.TYPESAFE_API_KEY;if(!key)return res.status(503).json({error:'jev_not_configured'});
 const labels=Object.keys(f.options);const orders=permutations(labels);const runs=[];const startedAll=performance.now();
 for(const order of orders){const criteria=Object.fromEntries(order.map((label,i)=>[`option_${i+1}`,f.options[label as keyof typeof f.options]]));const started=performance.now();const r=await fetch('https://api.typesafe.ai/v1/systemone',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'jev-1.13.0',state:{text:f.state},questions:{decision:{type:'choice',instructions:f.question,criteria}}})});if(!r.ok){console.error('order_bias_jev_failed',r.status);return res.status(503).json({error:'jev_unavailable'})}const body:any=await r.json();const a=body.answers?.decision||{};const raw=a.probabilities||a.distribution||{};const remapped:Record<string,number>={};order.forEach((label,i)=>remapped[label]=Number(raw[`option_${i+1}`]||0));const rawPick=String(a.choice||'');const idx=Number(rawPick.replace('option_',''))-1;const pick=order[idx]||rawPick;runs.push({order,pick,correct:pick===f.expected,probabilities:remapped,distributionConcentration:Number(a.confidence||0),latencyMs:Math.round(performance.now()-started),usage:body.usage||{},model:String(body.model||'jev-1.13.0')})}
 const canonical=runs[0];const flips=runs.filter(x=>x.pick!==canonical.pick).length;const divergences=runs.slice(1).map(x=>jsd(canonical.probabilities,x.probabilities,labels));const trajectory={schema:'jev-lab-trajectory-v1',cohortId:cohort.cohortId,fixture:f,controller:{model:'jev-1.13.0',rule:'six exhaustive permutations; semantic remap before metrics'},runs,summary:{permutations:runs.length,uniquePicks:[...new Set(runs.map(x=>x.pick))],flipRate:flips/runs.length,accuracy:runs.filter(x=>x.correct).length/runs.length,maxJsd:Math.max(0,...divergences),meanJsd:divergences.reduce((a,b)=>a+b,0)/(divergences.length||1),worstWrongConfidence:Math.max(0,...runs.filter(x=>!x.correct).map(x=>x.probabilities[x.pick]||0)),totalLatencyMs:Math.round(performance.now()-startedAll)},createdAt:new Date().toISOString()};const files={cohort:'order-bias-cohort-v1.json',trajectory:`trajectory-${f.id}.json`};return res.json({...trajectory,evidence:{files,sha256:{cohort:sha(cohort),trajectory:sha(trajectory)},replay:'Recompute summary from the six recorded, semantically remapped distributions. No provider call is required.'}})
}
type VercRequest=VercelRequest;type VercResponse=VercelResponse;
