import type{VercelRequest,VercelResponse}from'@vercel/node';import{createHash}from'node:crypto';
// Evidence Budget: Jev scores memory notes, picks which link type to follow, and says when there is enough.
// Code owns seeds, graph expansion, caps, validation, the stop rule, spend limits and the receipt. Jev never writes the answer.
// Read-path idea from Jev-Mem (Jiang, Li, Li; UT Dallas; arXiv 2609.23986). This is much smaller: hand-authored links, fixed caps, no write path.
const sha=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
type View='semantic'|'temporal'|'causal'|'entity';const VIEWS:View[]=['semantic','temporal','causal','entity'];
type Note={id:string;date:string;source:string;text:string;entities:string[];links:Record<View,string[]>};
const COHORT_VERSION='harbor-memory-v1';
const MEMORY:Note[]=[
{id:'m01',date:'2026-08-03',source:'standup notes',text:'Harbor app launch is planned for September 15, owned by Priya on the mobile team.',entities:['Harbor','Priya','mobile team'],links:{semantic:['m06','m10'],temporal:['m02'],causal:[],entity:['m04','m08']}},
{id:'m02',date:'2026-08-11',source:'security review',text:'Security review found that Harbor stores session tokens in plain local storage. Marked as a launch blocker.',entities:['Harbor','security review','session tokens'],links:{semantic:['m07'],temporal:['m01','m03'],causal:['m03','m05'],entity:['m07']}},
{id:'m03',date:'2026-08-14',source:'eng channel',text:'Diego started moving Harbor session tokens to the device keychain. Estimate: two weeks.',entities:['Harbor','Diego','keychain'],links:{semantic:['m07'],temporal:['m02','m04'],causal:['m05'],entity:['m09']}},
{id:'m04',date:'2026-08-20',source:'1:1 notes',text:'Priya asked for weekly launch updates to go to the #harbor-launch channel instead of email.',entities:['Priya','#harbor-launch'],links:{semantic:['m10'],temporal:['m03','m05'],causal:[],entity:['m01','m08']}},
{id:'m05',date:'2026-08-29',source:'planning meeting',text:'Harbor launch moved from September 15 to October 6 because the keychain migration will not finish in time.',entities:['Harbor','launch date','keychain'],links:{semantic:['m01','m10'],temporal:['m04','m06'],causal:['m06','m11'],entity:['m03']}},
{id:'m06',date:'2026-09-02',source:'marketing sync',text:'Marketing rebooked the Harbor launch webinar for October 8 to follow the new date.',entities:['Harbor','marketing','webinar'],links:{semantic:['m01'],temporal:['m05','m07'],causal:[],entity:['m12']}},
{id:'m07',date:'2026-09-05',source:'security review',text:'Follow-up security review passed after the keychain change was merged. Blocker closed.',entities:['Harbor','security review','keychain'],links:{semantic:['m02'],temporal:['m06','m08'],causal:['m11'],entity:['m02','m03']}},
{id:'m08',date:'2026-09-09',source:'org update',text:'Priya is on leave from September 20 to October 3. Sam covers Harbor launch decisions while she is out.',entities:['Priya','Sam','Harbor'],links:{semantic:[],temporal:['m07','m09'],causal:['m12'],entity:['m01','m04','m12']}},
{id:'m09',date:'2026-09-12',source:'eng channel',text:'Diego is moving to the payments team after Harbor ships.',entities:['Diego','payments team'],links:{semantic:[],temporal:['m08','m10'],causal:[],entity:['m03']}},
{id:'m10',date:'2026-09-14',source:'office chat',text:'Team lunch for the Harbor crew is on Friday at the ramen place near the office.',entities:['Harbor','lunch'],links:{semantic:['m01'],temporal:['m09','m11'],causal:[],entity:[]}},
{id:'m11',date:'2026-09-16',source:'release checklist',text:'Harbor release checklist is green except app store screenshots, due September 30.',entities:['Harbor','release checklist','screenshots'],links:{semantic:['m05'],temporal:['m10','m12'],causal:[],entity:['m12']}},
{id:'m12',date:'2026-09-18',source:'marketing sync',text:'Sam approved the final app store screenshots for Harbor.',entities:['Sam','Harbor','screenshots'],links:{semantic:['m11'],temporal:['m11'],causal:[],entity:['m08','m11']}}];
const EXAMPLES=[
{question:'When does Harbor launch now, and why did the date change?',gold:['m05']},
{question:'Who should approve Harbor launch decisions on September 25, and why not Priya?',gold:['m08']},
{question:'Is the Harbor security blocker resolved, and what fixed it?',gold:['m02','m07']}];const SCORE_LEVELS=['irrelevant','background only','partly answers','directly answers a needed part'];const SCORE_MAX=SCORE_LEVELS.length-1;
const PRICING={jevInputUsdPerMillion:.042,jevOutput:'free',asOf:'2026-09-23',source:'https://typesafe.ai/blog/introducing-system-one-models-and-jev'};
const POLICY={version:'evidence-budget-v3',maxRounds:4,callsPerRound:1,maxRequestInputTokens:8000,maxKeptNotes:6,maxCandidatesPerRound:5,keepThreshold:.5,stopThreshold:.7,jevTimeoutMs:8000,
 candidateOrder:'Frontier ids are sorted ascending; unseen ids beyond maxCandidatesPerRound are dropped for that round and may re-enter later only via links.',
 scoreNormalization:`Jev score answers are on a 0-${SCORE_MAX} level scale. normalized = score / ${SCORE_MAX}. If score is missing, normalized = expected level from probabilities / ${SCORE_MAX}. Values outside the scale, or probabilities that do not sum to 1 +/- 0.05, are invalid.`,
 rule:'Keep a candidate when normalized relevance >= .5 (level 1.5, between background only and partly answers). Stop complete only when validated P(enough) >= .7 and at least one note is kept. One Jev call per round, so the 4-round cap is also the call cap. Round cap, kept-note cap, the 8,000-token per-request input ceiling, graph exhaustion and no seed match stop incomplete with a warning. Any invalid, missing, or timed-out Jev answer stops fail-closed with the evidence so far, marked incomplete.'};
const LIMITS={perClientPerHour:6,instancePerHour:60,instancePerDay:300,maxTrackedClients:5000,cacheTtlMs:30*60*1000,killSwitch:'EVIDENCE_BUDGET_LIVE must equal 1 or live runs return 503 (default off).',clientKey:'x-vercel-forwarded-for, else x-real-ip, else x-forwarded-for. Vercel overwrites X-Forwarded-For to prevent spoofing (https://vercel.com/docs/headers/request-headers). Missing header -> one shared "unknown" bucket.',hardBounds:'Per request: at most 4 Jev calls and 8,000 input tokens, i.e. <= $0.000336 at the dated price. Per instance: <= 60 runs/hour and 300/day, i.e. <= $0.0202/hour and <= $0.101/day. Counters are in memory per instance, so the cross-instance total is not durable; the kill switch is the global stop.'};
const hits=new Map<string,number[]>();let hourHits:number[]=[],dayHits:number[]=[];const cache=new Map<string,{at:number;body:any}>();
const tok=(s:string)=>Math.max(1,Math.ceil(s.length/4));
const words=(s:string)=>new Set(s.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>3));
function seeds(q:string){const qw=words(q);return MEMORY.map(m=>{const mw=words(m.text+' '+m.entities.join(' '));let o=0;qw.forEach(w=>{if(mw.has(w))o++});return{id:m.id,o}}).filter(x=>x.o>0).sort((a,b)=>b.o-a.o||a.id.localeCompare(b.id)).slice(0,3).map(x=>x.id).sort()}
const inUnit=(n:unknown)=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=1;
function probs(p:any,keys:string[]){if(!p||typeof p!=='object')return null;const vals=keys.map(k=>p[k]);if(!vals.every(inUnit))return null;const sum=vals.reduce((a:number,b:number)=>a+b,0);return Math.abs(sum-1)<=.05?Object.fromEntries(keys.map((k,i)=>[k,vals[i]])):null}
export function readScore(a:any){const levels=Array.from({length:SCORE_MAX+1},(_,i)=>String(i));const p=probs(a?.probabilities,levels);const expected=p?levels.reduce((s,k)=>s+Number(k)*p[k],0):null;
 if(typeof a?.score==='number'&&Number.isFinite(a.score)){if(a.score<0||a.score>SCORE_MAX)return{ok:false as const,reason:'score_out_of_range',raw:a.score};return{ok:true as const,normalized:a.score/SCORE_MAX,path:'score',raw:a.score,expectedFromProbabilities:expected,mismatch:expected!==null&&Math.abs(expected-a.score)>.25}}
 if(expected!==null)return{ok:true as const,normalized:expected/SCORE_MAX,path:'probabilities_expected',raw:expected,expectedFromProbabilities:expected,mismatch:false};return{ok:false as const,reason:'score_missing_or_malformed',raw:a?.score??null}}
export function readEnough(a:any){const p=probs(a?.probabilities,['enough','more']);return p?{ok:true as const,pEnough:p.enough}:{ok:false as const,reason:'enough_probabilities_invalid'}}
export function readView(a:any){const p=probs(a?.probabilities,VIEWS);const c=a?.choice;if(!p||!VIEWS.includes(c))return{ok:false as const,reason:'view_invalid'};return{ok:true as const,view:c as View,probabilities:p}}
async function jev(state:unknown,questions:unknown){const began=performance.now();let r:Response;try{r=await fetch('https://api.typesafe.ai/v1/systemone',{method:'POST',headers:{Authorization:`Bearer ${process.env.TYPESAFE_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:'jev-1.13.0',state,questions}),signal:AbortSignal.timeout(POLICY.jevTimeoutMs)})}catch(e:any){throw Object.assign(Error(e?.name==='TimeoutError'?'jev_timeout':'jev_network_error'),{ms:Math.round(performance.now()-began)})}const ms=Math.round(performance.now()-began);if(!r.ok)throw Object.assign(Error(`jev_${r.status}`),{ms});const b:any=await r.json();const reported=Number(b.usage?.input_tokens);return{answers:b.answers||{},model:String(b.model||'jev-1.13.0'),inputTokens:Number.isFinite(reported)&&reported>0?reported:tok(JSON.stringify({state,questions})),tokenSource:Number.isFinite(reported)&&reported>0?'provider_usage':'estimated_chars_div_4',outputTokens:Number(b.usage?.output_tokens)||0,ms}}
const clientKey=(req:VercelRequest)=>{const h=req.headers||{};const v=h['x-vercel-forwarded-for']||h['x-real-ip']||h['x-forwarded-for'];return String(Array.isArray(v)?v[0]:v||'unknown').split(',')[0].trim()||'unknown'};
export function allow(key:string,now=Date.now()){const H=3600e3,D=24*H;hourHits=hourHits.filter(t=>now-t<H);dayHits=dayHits.filter(t=>now-t<D);
 for(const[k,v]of hits){const f=v.filter(t=>now-t<H);if(f.length)hits.set(k,f);else hits.delete(k)}
 const mine=hits.get(key)||[];if(mine.length>=LIMITS.perClientPerHour||hourHits.length>=LIMITS.instancePerHour||dayHits.length>=LIMITS.instancePerDay)return false;
 if(!hits.has(key)&&hits.size>=LIMITS.maxTrackedClients)return false;mine.push(now);hits.set(key,mine);hourHits.push(now);dayHits.push(now);return true}
export const limiterSize=()=>hits.size;
export default async function handler(req:VercelRequest,res:VercelResponse){res.setHeader('Cache-Control','no-store');
if(req.method==='GET')return res.status(200).json({cohort:COHORT_VERSION,cohortSha256:sha(MEMORY),memory:MEMORY,examples:EXAMPLES,policy:POLICY,limits:LIMITS,pricing:PRICING});
if(req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});const question=typeof req.body?.question==='string'?req.body.question.trim():'';if(question.length<5||question.length>500)return res.status(400).json({error:'question_must_be_5_to_500_chars'});if(process.env.EVIDENCE_BUDGET_LIVE!=='1')return res.status(503).json({error:'live_runs_disabled'});if(!process.env.TYPESAFE_API_KEY)return res.status(503).json({error:'jev_not_configured'});
const hit=cache.get(question);if(hit&&Date.now()-hit.at<LIMITS.cacheTtlMs)return res.status(200).json({...hit.body,cached:true});
if(!allow(clientKey(req)))return res.status(429).json({error:'rate_limited',limits:LIMITS});
const began=performance.now();const kept=new Set<string>(),seen=new Set<string>();const rounds:any[]=[];const seedIds=seeds(question);let frontier=seedIds,stop='',calls=0,jevTokens=0,tokenSources=new Set<string>(),jevModel='jev-1.13.0';
if(!frontier.length)stop='no_seed_match';
while(!stop){if(rounds.length>=POLICY.maxRounds){stop='round_cap';break}
 const cands=frontier.filter(id=>!seen.has(id)).sort().slice(0,POLICY.maxCandidatesPerRound);if(!cands.length){stop='graph_exhausted';break}cands.forEach(id=>seen.add(id));
 const keptEvidence=[...kept].sort().map(id=>({id,text:MEMORY.find(m=>m.id===id)!.text}));const candidates=cands.map(id=>({id,text:MEMORY.find(m=>m.id===id)!.text}));
 const questions:any={enough:{type:'choice',instructions:'Using only the kept evidence plus the candidates, is there enough evidence to answer every part of the question, such as when, why, or who?',criteria:{enough:'The evidence answers every part of the question',more:'Some part of the question is still unsupported'}},view:{type:'choice',instructions:'If more evidence is needed, which kind of link is most likely to lead to it?',criteria:{semantic:'Notes about the same topic',temporal:'Notes just before or after in time',causal:'Notes about causes or consequences',entity:'Notes about the same person, team, or system'}}};
 cands.forEach((id,i)=>{questions[`c${i}`]={type:'score',instructions:`Score how much candidate note ${id} helps answer the question. Candidate ${id}: "${candidates[i].text}"`,criteria:SCORE_LEVELS}});
 const request={state:{question,keptEvidence,candidates},questions};const ceiling=Math.min(POLICY.maxRequestInputTokens,Number(process.env.EVIDENCE_BUDGET_MAX_TOKENS)||Infinity);if(jevTokens+tok(JSON.stringify(request))>ceiling){stop='token_ceiling';break}let j;
 try{j=await jev(request.state,questions)}catch(e:any){stop='controller_unavailable_fail_closed';rounds.push({round:rounds.length+1,candidateIds:cands,request,error:String(e?.message||e),latencyMs:e?.ms??0});break}
 calls++;jevTokens+=j.inputTokens;tokenSources.add(j.tokenSource);jevModel=j.model;
 const scores=cands.map((id,i)=>({id,...readScore(j.answers[`c${i}`])}));const en=readEnough(j.answers.enough);const vw=readView(j.answers.view);
 const round:any={round:rounds.length+1,candidateIds:cands,request,rawAnswers:j.answers,scores,latencyMs:j.ms,inputTokens:j.inputTokens,tokenSource:j.tokenSource};rounds.push(round);
 const badScore=scores.find(s=>!s.ok);if(badScore){stop='invalid_score_fail_closed';round.invalid=badScore;break}if(!en.ok){stop='invalid_enough_fail_closed';round.invalid=en;break}
 scores.forEach(s=>{if(s.ok&&s.normalized>=POLICY.keepThreshold&&kept.size<POLICY.maxKeptNotes)kept.add(s.id)});round.kept=[...kept].sort();round.pEnough=en.pEnough;
 if(en.pEnough>=POLICY.stopThreshold&&kept.size){stop='controller_enough';break}if(kept.size>=POLICY.maxKeptNotes){stop='kept_cap';break}
 if(!vw.ok){stop='invalid_view_fail_closed';round.invalid=vw;break}round.nextView=vw.view;round.viewProbabilities=vw.probabilities;
 const next=new Set<string>();[...kept].sort().forEach(id=>MEMORY.find(m=>m.id===id)!.links[vw.view].forEach(n=>{if(!seen.has(n))next.add(n)}));frontier=[...next].sort()}
const packet=[...kept].sort().map(id=>MEMORY.find(m=>m.id===id)!);const complete=stop==='controller_enough'&&packet.length>0;
const warning=complete?null:/fail_closed/.test(stop)?'Jev answer missing, invalid, or timed out. Evidence is partial.':stop==='no_seed_match'?'No memory note shares words with the question. Nothing was searched.':stop==='token_ceiling'?'Stopped at the per-request Jev input-token ceiling. Treat the packet as incomplete.':'Search stopped on a cap or ran out of links before Jev judged the evidence sufficient. Treat the packet as incomplete.';
const fullTokens=tok(MEMORY.map(m=>m.text).join('\n'));const packetTokens=tok(packet.map(m=>m.text).join('\n'));
const ex=EXAMPLES.find(e=>e.question===question);const check=ex?{gold:ex.gold,recall:ex.gold.filter(g=>kept.has(g)).length/ex.gold.length,precision:kept.size?[...kept].filter(k=>ex.gold.includes(k)).length/kept.size:0,missing:ex.gold.filter(g=>!kept.has(g)),extra:[...kept].filter(k=>!ex.gold.includes(k)).sort()}:null;
const replayCore={schema:'jev-lab-evidence-budget-v2',input:{question,questionSha256:sha(question)},cohort:{version:COHORT_VERSION,sha256:sha(MEMORY),notes:MEMORY},frozenPolicy:POLICY,limits:LIMITS,seeds:seedIds,rounds:rounds.map(({latencyMs,...r})=>r),outcome:{stopReason:stop,complete,warning,evidencePacket:packet.map(m=>({id:m.id,date:m.date,source:m.source,text:m.text})),controllerCalls:calls,notesInspected:seen.size,notesInMemory:MEMORY.length},check,provenance:{controller:jevModel,controllerRoute:'direct-typesafe',endpoint:'https://api.typesafe.ai/v1/systemone',answerModel:'none - this app returns the evidence packet only'}};
const body={...replayCore,runId:`evidence-budget-${Date.now()}`,createdAt:new Date().toISOString(),cached:false,
 economics:{currency:'USD',pricingSnapshot:PRICING,jevInputTokens:jevTokens,jevTokenSource:[...tokenSources].join('+')||'none',jevEstimatedCostUsd:jevTokens*PRICING.jevInputUsdPerMillion/1e6,label:'Estimated from input tokens and the dated public price. Not charged spend.',answerContextTokensEstimated:{method:'chars_div_4',fullMemory:fullTokens,evidencePacket:packetTokens,controllerReadVsSaved:{controllerRead:jevTokens,downstreamSaved:fullTokens-packetTokens}}},
 latency:{totalMs:Math.round(performance.now()-began),perRoundMs:rounds.map(r=>r.latencyMs)},
 evidence:{replayCoreSha256:sha(replayCore),hashScope:'sha256 of JSON.stringify(replayCore): input, enclosed cohort, frozen policy, seeds, every round request and raw Jev answer, outcome, check, provenance. Excludes runId, createdAt, cached, latency and economics. Unsigned.',replay:'Recompute seeds from word overlap. For each round re-apply readScore/readEnough/readView and frozenPolicy to rawAnswers to recompute kept notes, next frontier and stop reason. Recompute cost from jevInputTokens and pricingSnapshot.'}};
if(complete||stop==='no_seed_match')cache.set(question,{at:Date.now(),body});return res.status(200).json(body)}
